-- PostgreSQL/Supabase reference schema for the production migration.
create extension if not exists pgcrypto;
create table if not exists departments(id uuid primary key default gen_random_uuid(), name text not null, code text unique not null);
create table if not exists users(id uuid primary key, name text not null, email text unique not null, role text not null check(role in ('student','faculty','admin')), department_id uuid references departments(id), avatar text, office_location text, bio text, created_at timestamptz default now());
create table if not exists subjects(id uuid primary key default gen_random_uuid(), name text not null, code text unique not null, department_id uuid references departments(id));
create table if not exists faculty_subjects(faculty_id uuid references users(id) on delete cascade, subject_id uuid references subjects(id) on delete cascade, primary key(faculty_id,subject_id));
create table if not exists office_hours(id uuid primary key default gen_random_uuid(), faculty_id uuid references users(id) on delete cascade, day_of_week int, start_time time not null, end_time time not null, location text, status text default 'active', recurring boolean default true, specific_date date, created_at timestamptz default now());
create table if not exists blocked_slots(id uuid primary key default gen_random_uuid(), faculty_id uuid references users(id) on delete cascade, start_at timestamptz not null, end_at timestamptz not null, reason text);
create table if not exists appointments(id uuid primary key default gen_random_uuid(), student_id uuid references users(id), faculty_id uuid references users(id), subject_id uuid references subjects(id), start_at timestamptz not null, end_at timestamptz not null, status text not null, reason text, mode text not null, location text, cancelled_by uuid, cancel_reason text, created_at timestamptz default now(), updated_at timestamptz default now());
create index if not exists appointments_faculty_time on appointments(faculty_id,start_at,end_at);
create table if not exists waitlist(id uuid primary key default gen_random_uuid(), student_id uuid references users(id), faculty_id uuid references users(id), subject_id uuid references subjects(id), preferred_date date, preferred_start time, preferred_end time, appointment_type text default 'in-person', status text default 'waiting', offered_appointment_id uuid, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists notifications(id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade, type text not null, title text not null, message text not null, read boolean default false, created_at timestamptz default now());
create table if not exists no_show_scores(id uuid primary key default gen_random_uuid(), appointment_id uuid unique references appointments(id) on delete cascade, score int not null, risk_level text not null, factors jsonb not null, created_at timestamptz default now());
