import {randomUUID} from 'node:crypto';
import {getDb} from './db';
import {addDays,isoNow,localDate,minutes} from './utils';

const ACTIVE=["pending","confirmed"];
export function overlaps(aStart:string,aEnd:string,bStart:string,bEnd:string){return aStart<bEnd && aEnd>bStart}
export function getOfficeWindow(facultyId:string,date:string,start:string,end:string){const db=getDb();const dow=new Date(`${date}T12:00:00`).getDay();return db.prepare(`SELECT * FROM office_hours WHERE faculty_id=? AND status='active' AND ((recurring=1 AND day_of_week=?) OR (recurring=0 AND specific_date=?))`).all(facultyId,dow,date).some((h:any)=>minutes(start)>=minutes(h.start_time)&&minutes(end)<=minutes(h.end_time))}
export function isBlocked(facultyId:string,start:string,end:string){const rows=getDb().prepare('SELECT * FROM blocked_slots WHERE faculty_id=?').all(facultyId) as any[];return rows.some(x=>overlaps(start,end,x.start_at,x.end_at))}
export function findConflict(facultyId:string,start:string,end:string,excludeId?:string){const q=`SELECT * FROM appointments WHERE faculty_id=? AND status IN ('pending','confirmed') AND start_at < ? AND end_at > ? ${excludeId?'AND id<>?':''} LIMIT 1`;return (excludeId?getDb().prepare(q).get(facultyId,end,start,excludeId):getDb().prepare(q).get(facultyId,end,start)) as any}
export function validateSlot(facultyId:string,date:string,time:string,duration=30,excludeId?:string){const start=`${date} ${time}:00`,total=minutes(time)+duration,hh=String(Math.floor(total/60)).padStart(2,'0'),mm=String(total%60).padStart(2,'0'),end=`${date} ${hh}:${mm}:00`;if(new Date(start.replace(' ','T')).getTime()<=Date.now())return {ok:false,error:'Please choose a future time.'};if(!getOfficeWindow(facultyId,date,time,end.slice(11,16)))return {ok:false,error:'This time is outside the faculty office hours.'};if(isBlocked(facultyId,start,end))return {ok:false,error:'This period is blocked by the faculty.'};const conflict=findConflict(facultyId,start,end,excludeId);if(conflict)return {ok:false,error:'That slot is already booked.',conflict};return {ok:true,start,end}}
export function generateSlots(facultyId:string,fromDate=localDate(),days=14){const db=getDb();const slots:any[]=[];for(let i=0;i<days;i++){const date=addDays(fromDate,i),dow=new Date(`${date}T12:00:00`).getDay();const hours=db.prepare(`SELECT * FROM office_hours WHERE faculty_id=? AND status='active' AND ((recurring=1 AND day_of_week=?) OR (recurring=0 AND specific_date=?))`).all(facultyId,dow,date) as any[];for(const h of hours){for(let m=minutes(h.start_time);m+30<=minutes(h.end_time);m+=30){const hh=String(Math.floor(m/60)).padStart(2,'0'),mm=String(m%60).padStart(2,'0'),time=`${hh}:${mm}`,v=validateSlot(facultyId,date,time);if(v.ok)slots.push({date,time,start:v.start,end:v.end,location:h.location})}}}return slots}
export function findAlternatives(facultyId:string,requestedDate:string,requestedTime:string,subjectId?:string){const requested=`${requestedDate} ${requestedTime}`;const slots=generateSlots(facultyId,requestedDate,7);return slots.map(s=>({...s,score:Math.abs(new Date(s.start.replace(' ','T')).getTime()-new Date(requested.replace(' ','T')).getTime())/60000 + (s.date===requestedDate?0:180)})).sort((a,b)=>a.score-b.score).slice(0,3)}
export function createNotification(userId:string,type:string,title:string,message:string){getDb().prepare('INSERT INTO notifications VALUES(?,?,?,?,?,?,?)').run(randomUUID(),userId,type,title,message,0,isoNow())}
export function calculateNoShowScore(studentId:string,appointmentId?:string){const db=getDb();const noShows=(db.prepare("SELECT COUNT(*) c FROM appointments WHERE student_id=? AND status='no_show'").get(studentId) as any).c;const lateCancels=(db.prepare("SELECT COUNT(*) c FROM appointments WHERE student_id=? AND status='cancelled' AND julianday(updated_at)-julianday(start_at) < 1").get(studentId) as any).c;const upcoming=(db.prepare("SELECT COUNT(*) c FROM appointments WHERE student_id=? AND start_at>? AND status IN ('pending','confirmed')").get(studentId,isoNow()) as any).c;const appt=appointmentId?(db.prepare('SELECT created_at,start_at FROM appointments WHERE id=?').get(appointmentId) as any):null;let score=20;const factors:string[]=[];if(noShows){score+=30;factors.push('Previous no-show')}if(lateCancels){score+=20;factors.push('Previous late cancellation')}if(appt&&new Date(appt.start_at.replace(' ','T')).getTime()-new Date(appt.created_at.replace(' ','T')).getTime()<24*3600*1000){score+=10;factors.push('Short booking lead time')}if(upcoming>1){score+=10;factors.push('Multiple upcoming appointments')}if(noShows===0&&lateCancels===0){score-=15;factors.push('Strong attendance history')}score=Math.max(0,Math.min(100,score));const risk=score<=30?'low':score<=60?'medium':'high';return {score,riskLevel:risk,factors}}
export function scoreAppointment(appointmentId:string){const db=getDb();const a=db.prepare('SELECT student_id FROM appointments WHERE id=?').get(appointmentId) as any;if(!a)return null;const r=calculateNoShowScore(a.student_id,appointmentId);db.prepare('INSERT OR REPLACE INTO no_show_scores VALUES(?,?,?,?,?,?)').run(randomUUID(),appointmentId,r.score,r.riskLevel,JSON.stringify(r.factors),isoNow());return r}
export function fulfillWaitlist(facultyId:string,start:string,end:string){const db=getDb();const entries=db.prepare(`SELECT w.*,u.name studentName FROM waitlist w JOIN users u ON u.id=w.student_id WHERE w.faculty_id=? AND w.status='waiting' ORDER BY CASE WHEN preferred_date=? THEN 0 ELSE 1 END,created_at`).all(facultyId,start.slice(0,10)) as any[];const candidate=entries.find(w=>{const ps=w.preferred_start?minutes(w.preferred_start):0,pe=w.preferred_end?minutes(w.preferred_end):1440,sm=minutes(start.slice(11,16));return (!w.preferred_date||w.preferred_date===start.slice(0,10))&&sm>=ps&&sm<pe});if(!candidate)return null;const id=randomUUID(),now=isoNow();db.prepare('INSERT INTO appointments VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,candidate.student_id,facultyId,candidate.subject_id,start,end,'confirmed','Waitlist auto-fill','in-person',null,null,null,now,now);db.prepare("UPDATE waitlist SET status='filled',offered_appointment_id=?,updated_at=? WHERE id=?").run(id,now,candidate.id);createNotification(candidate.student_id,'waitlist','Slot available',`A cancelled slot at ${start.slice(11,16)} is now reserved for you.`);return {appointmentId:id,studentId:candidate.student_id}}
