import {getDb} from './db';import type {Department,Subject,User,OfficeHour,NotificationRow} from './types';import {generateSlots,calculateNoShowScore} from './business';
export function getUserById(id:string){return getDb().prepare('SELECT * FROM users WHERE id=?').get(id) as User|undefined}
export function getDepartments(){return getDb().prepare('SELECT * FROM departments ORDER BY name').all() as Department[]}
export function getAllSubjects(){return getDb().prepare('SELECT * FROM subjects ORDER BY name').all() as Subject[]}
export function getSubjectsForFaculty(id:string){return getDb().prepare('SELECT s.* FROM subjects s JOIN faculty_subjects fs ON fs.subject_id=s.id WHERE fs.faculty_id=? ORDER BY s.name').all(id) as Subject[]}
export function getOfficeHoursForFaculty(id:string){return getDb().prepare('SELECT * FROM office_hours WHERE faculty_id=? ORDER BY day_of_week,start_time').all(id) as OfficeHour[]}
export function listFaculty(filters:any={}){const db=getDb();let sql=`SELECT u.*,d.name departmentName FROM users u LEFT JOIN departments d ON d.id=u.department_id WHERE u.role='faculty'`;const args:any[]=[];if(filters.department){sql+=' AND u.department_id=?';args.push(filters.department)}if(filters.search){sql+=' AND (lower(u.name) LIKE ? OR lower(u.email) LIKE ?)';const q=`%${filters.search.toLowerCase()}%`;args.push(q,q)}if(filters.subject){sql+=' AND EXISTS (SELECT 1 FROM faculty_subjects fsf WHERE fsf.faculty_id=u.id AND fsf.subject_id=?)';args.push(filters.subject)}let rows=db.prepare(sql+' ORDER BY u.name').all(...args) as any[];return rows.map(f=>{const subjects=getSubjectsForFaculty(f.id);const slots=generateSlots(f.id);return {...f,subjects,subjectNames:subjects.map(s=>s.name),nextSlot:slots[0]||null,bookedCount:(db.prepare("SELECT COUNT(*) c FROM appointments WHERE faculty_id=? AND status IN ('pending','confirmed','completed')").get(f.id) as any).c,availability:slots.length?'Available':'Full'}})}
export function listAppointmentsForUser(id:string,role:string){const db=getDb();const q=role==='student'?`SELECT a.*,u.name facultyName,u.title facultyTitle,u.office_location,s.name subjectName FROM appointments a JOIN users u ON u.id=a.faculty_id LEFT JOIN subjects s ON s.id=a.subject_id WHERE a.student_id=? ORDER BY a.start_at DESC`:`SELECT a.*,u.name studentName,s.name subjectName FROM appointments a JOIN users u ON u.id=a.student_id LEFT JOIN subjects s ON s.id=a.subject_id WHERE a.faculty_id=? ORDER BY a.start_at DESC`;const rows=db.prepare(q).all(id) as any[];return rows.map(a=>({...a,risk:role==='student'?calculateNoShowScore(id,a.id):calculateNoShowScore(a.student_id,a.id)}))}
export function listNotifications(id:string,limit=50){return getDb().prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT ?').all(id,limit) as NotificationRow[]}
